### ISSUE TITLE
Run selenium server, using docker inside binder

### ISSUE THREAD

**Issue by hliebert** [jupyterhub/binderhub#1072]
I am preparing some lectures in which students use `library(RSelenium)` in `R`. This requires that the students launch a selenium server in a container:

```
docker run -d -p 4445:4444 selenium/standalone-firefox:2.53.1
```

What would be the best way to achieve this functionality?

**Comment by betatim** [comment]
Hi there 👋!

Can we move this discussion to http://discourse.jupyter.org/ (where most of the people who hang out here also hang out, as well as more people). We are trying to streamline the [different discussion places](https://discourse.jupyter.org/t/a-proposal-for-jupyterhub-communications/505) and want to use the issues on GitHub repos for technical discussions on how to change the contents of the repo. More general discussions should go to discourse so that they are easier to find, better indexed by google and generally more accessible than being hidden in the bowls of a GitHub repository ;)

Without knowing much about selenium or how the R library uses it: you can't start an additional container in binder. You only get one. However you should be able to install selenium in that container and start a selenium server/process. Once you know which commands to run take a look at https://repo2docker.readthedocs.io/en/latest/config_files.html the various config files we support to perform the steps you need to run.

Thanks!

**Comment by hliebert** [comment]
Sorry for posting in the wrong channel, I'll close it and will ask elsewhere as suggested.
