### ISSUE TITLE
Rstudio terminal errors

### ISSUE THREAD

**Issue by sje30** [jupyterhub/binderhub#1095]
### Bug description

If I launch

https://mybinder.org/v2/gh/binder-examples/r/master?urlpath=rstudio

and then ask for a Terminal (Tools -> Terminal -> New Terminal) , I get the following error

```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.

```

and after typing what it says, and starting a new terminal, I get the same error.

(the terminal in Jupyter works fine.)

#### Expected behaviour

I thought the error would not appear!

### How to reproduce

See above.

### Your personal set up

Manjaro Linux stable

**Comment by betatim** [comment]
This doesn't happen if you start a terminal via the Jupyter notebook UI.

Could this be because there is a difference in the kind of terminal RStudio vs Jupyter start/ For example a "login shell" or not? I don't know enough about the finer points here but this is the direction I'd investigate in.

To fix this https://github.com/jupyter/repo2docker is the place where the work needs to happen.

**Comment by manics** [comment]
Hi :wave: This is an old issue which doesn't sound like a BinderHub bug so I'm closing it. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
