### ISSUE TITLE
New gist does not start building

### ISSUE THREAD

**Issue by renefritze** [jupyterhub/binderhub#1171]
### Bug description

I tried to run a [new gist](https://gist.github.com/renefritze/57db73707f97ed0bd4eb600a1a6f9ab3) 
Even after multiple refreshes on a vanilla Firefox  the binder interface seems stuck on "waiting to build". 
Trying [a gist](https://gist.github.com/renefritze/14c5f2d79694ff746e7b0905a773e03c) I created 7 months ago seems to work fine (as in a jupyterhub instance is spawned).

While this might be somewhat related to #1168, after cloning to my machine both gists have a master branch checked out afterwards.

**Comment by betatim** [comment]
I don't think this is related to the main/master branch change. For me the new gist started building when I visited https://mybinder.org/v2/gist/renefritze/57db73707f97ed0bd4eb600a1a6f9ab3/master

Do you use browser extensions that block trackers/adverts? We continue to have situations where those block requests. We think this is because mybinder.org is actually a group of clusters and some of the network requests we make look similar to what a advertising/user tracker would do.

To test this hypothesis: what happens if you visit https://gke2.mybinder.org/v2/gist/renefritze/57db73707f97ed0bd4eb600a1a6f9ab3/master, does the build start? This explicitly selects one of the clusters where we don't normally have this problem (the drawback is that if this cluster is down your link won't work, which is why we don't recommend "hard coding" like this)

**Comment by renefritze** [comment]
> Do you use browser extensions that block trackers/adverts? We continue to have situations where those block requests. We think this is because mybinder.org is actually a group of clusters and some of the network requests we make look similar to what a advertising/user tracker would do.

I've tried this with a Firefox that has no plugins installed. However my home network's DNS is routed through a PiHole. I can try again with that disabled (and maybe looking at the queries in PiHole's log?) later today if you think that's worth doing.

> To test this hypothesis: what happens if you visit https://gke2.mybinder.org/v2/gist/renefritze/57db73707f97ed0bd4eb600a1a6f9ab3/master, does the build start?

Yes, it starts just fine.

**Comment by manics** [comment]
Hi :wave: This is an old issue which doesn't sound like a BinderHub bug so I'm closing it. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
