### ISSUE TITLE
Reduce the image build tests to reduce CI times from ~13 minutes

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/binderhub#1199]
https://github.com/jupyterhub/binderhub/blob/71896a68432dd97500f36b03399c8922953c7a7a/binderhub/tests/test_build.py#L18-L28

This test is run four times as it pass four different versions of the parameters. I'd like to make it faster, because we wait several minutes here and I bet we can test the same details with at least one less build.

- The first build takes a long time, its the first.
- The second is done very quickly because it is the same as the first in practice and has been completed already.
- The third is another build which takes significant time, and if the point is to test building a branch, we can perhaps instead create a branch matching that commit, or create a tag matching this commit instead?
- The fourth is a new build again, and takes some time.

## I suggest the following
- [x] Optimize third test, which is about using a not already resolved (https://github.com/jupyterhub/binderhub/commit/db9029f4ccdfe0987e3fc41b2436c5fe2d6f01d9), to reference to point to a tag to the same commit we have already built.
  - It seems that two new commits have been added, so master is now different from what it was before. Since those commits are about performance, we want to start pointing to master again with the first two builds, which is commit hash 20c4fe55a9b2c5011d228545e821b1c7b1723652.
- [x] We stop doing a second build from scratch, and only do one. The second new repo build is to test against GitLab as well as GitHub, but I think we can settle for just GitHub as its repo2docker's job to fix the functionality of all different providers mainly.
- [x] We trivialize the build. Ah, this is already done in https://github.com/jupyterhub/binderhub/commit/be975033516cf3c71cfa5e4256cc6309a4069c9f
- [ ] We could perhaps even do `docker pull` on something that makes us only do a very silly final step in the build rather than a full rebuild that does all the repo2docker stuff from scratch?

**Comment by betatim** [comment]
Moving the two commits is a good idea. Maybe we can even add a comment to this test instructing future us that the commits should match master so that in the future we don't arrive here and think "this would be faster if the commits matched `master` but maybe these commits were selected on purpose. Let me research."

I'd like to keep the GitLab build. Tests like these got added because people inadvertently broke the case the tests cover. Which then leads to things being broken in production on mybinder.org. Spending a few minutes of CI time (even per build) is a good investment because it uses a resource we have a lot of (CI build minutes) and saves human time which we don't have a lot of. For fast(er) local development we can only run the tests relevant to the changes we've made, just run the tests added for the feature we are working on or we can tag tests as "fast" and "slow" so you can select them with a command-line flag. And leave running the full set of tests to the CI. Furthermore the general agreement for this repository is that people do not merge their own PRs. Typically it takes someone else more than a few minutes to arrive and have reviewed work.

Asking a second person to merge PRs instead of self merging help slow down the rate of change. This is a good thing. It gives the author time to think for a second time about their changes, it keeps a second person in the loop about changes (most people do not work full time on this so they have limited bandwidth), it gives a second person a chance to learn about the topic (learning interesting things from experts is IMHO one of the main reasons people spend free time on projects) and review by peers produces higher quality work. In the moment waiting for a second person feels like a big burden and slowdown but like the sync-vs-async communication discussion in the long term peer review wins in terms of productivity, quality and inclusiveness (just like async communication does).
