### ISSUE TITLE
denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by nikl11** [jupyterhub/binderhub#1320]
Hello, I built my binderhub using the "zero to binderhub", where as a repository I chose the docker hub. I created my docker hub account to which I can push images manually via 'docker push'. But despite having 

registry:
  username: <dockerhub-id>
  password: <dockerhub-password>

in my secret.yaml and
config:
  BinderHub:
    use_registry: true
    image_prefix: <dockerhub-id>/binder-meta-

 in my config. yaml (the id and password within <> brackets is what I use to login to hub.docker.com),  my image building process ends with an error message 

...
Succesfully built ....
Succesfully tagged ...
denied: requested access to the resource is denied

where docker hub seems to deny the image upload request. Has anybody encountered this? I have no idea what the problem might be.

**Comment by manics** [comment]
Hi :wave: This sounds like a configuration problem rather than a bug. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead?

When you do so please format your configuration as code with triple backticks https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks

As you can see in your description some of the key formatting has been lost which means it's not possible to review your configuration properly.
