### ISSUE TITLE
Binder not working in a sub-directory

### ISSUE THREAD

**Issue by HarshCasper** [jupyterhub/binderhub#1338]
### Bug description

Hi :wave: 

I am working on developing a [Jupyter Wrapper Kernel](https://github.com/metacall/jupyter-kernel) for the [MetaCall Core](https://github.com/metacall/core) library. We have a Dockerfile specified [here](https://github.com/metacall/jupyter-kernel/blob/master/Dockerfile) that allows us to spin a Binder where we can try out the examples. 

Unfortunately, this doesn't work with the sub-directories like `examples` where we host all of our example notebooks. It just displays `Kernel starting..` and asks us to wait. This leads to a bad UX since most users would employ the use of example notebooks to try out the kernel.

#### Expected behaviour

The notebooks in the examples sub-directory should work and execute the code.

#### Actual behaviour

The notebooks in the examples sub-directory do not work and do not execute the code.

### How to reproduce

- Start the Binder instance [here](https://mybinder.org/v2/gh/metacall/jupyter-kernel/master).
- Go to the examples sub-directory and try executing a notebook.
- `Kernel starting, please wait` would be shown.

**Comment by manics** [comment]
Sorry for the slow response. Have you tried reproducing the error locally with repo2docker?

This sounds like a problem specific to your kernel rather than a bug in binder or repo2docker, but if you can demonstrate a bug please open a new issue with specific details.

If you need more help would you mind posting on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions 😀.
