### ISSUE TITLE
Update JupyterHub Version in Image Definition

### ISSUE THREAD

**Issue by rpwagner** [jupyterhub/binderhub#1515]
### Proposed change

The most recent tag for [jupyterhub/k8s-binderhub](https://hub.docker.com/r/jupyterhub/k8s-binderhub/tags) is `0.2.0-n956.h64a6ec4` and builds with `jupyterhub==1.5.*`.  I'm assuming this based on the current [`helm-chart/images/binderhub/requirements.in`](https://github.com/jupyterhub/binderhub/blob/0fa35a06e7f7d054f8bb8dd2cba158ed7f45ac68/helm-chart/images/binderhub/requirements.in#L8).

I suggest that the image build be updated to match the top-level [`requirements.txt`](https://github.com/jupyterhub/binderhub/blob/master/requirements.txt), or the version in the latest [Z2JH hub image definition](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/images/hub/requirements.in).

### Who would use this feature?

All users of the `[jupyterhub/k8s-binderhub` image or its definition.

### (Optional): Suggest a solution

I was able to build the image without pinning the JupyterHub version, which uses the top-level `binderhub/requirements.txt`. However, I have not tested the image, which was why I haven't submitted a PR. Plus, I'm not sure of what other dependencies might be impacted, or if I'm even looking at the correct build definition.

**Comment by consideRatio** [comment]
I figure the version used in binderhub should match the one used in z2jh helm chart it depends on.

The z2jh version used by binderhub is 1.2.0: https://github.com/jupyterhub/binderhub/blob/0fa35a06e7f7d054f8bb8dd2cba158ed7f45ac68/helm-chart/binderhub/Chart.yaml#L14-L16

The jupyterhub version used by z2jh 1.2.0 is jupyterhub 1.5.0 https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/1.2.0/images/hub/requirements.txt#L55

Since binderhub uses the latest z2jh, I consider this as good for now.

**Comment by rpwagner** [comment]
@consideRatio I can understand that. And it looks like z2jh is getting closer to a 2.0 release which will include moving to a more recent version of JH. So it would make since to update BinderHub after z2jh, when you can pin the new chart version.
