### ISSUE TITLE
`.binder` will be hidden in the notebook UI

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#157]
I just realized that per (https://github.com/jupyter/notebook/issues/2382), if people use a `.binder` folder to contain all of their binder build files, then it won't show up in the jupyter notebooks in Binder. Are we fine with that? I could see it causing some confusion...

**Comment by minrk** [comment]
I think that's okay, and possibly desirable.

**Comment by choldgraf** [comment]
I think we should document it though - people are gonna be confused if they put a folder in their git repository, and then it doesn't show up when people open up Binder, no?

**Comment by minrk** [comment]
Oh, yes. When we add Binder docs explaining about the .binder folder we should definitely mention that it's a hidden folder.

**Comment by minrk** [comment]
https://github.com/jupyter/repo2docker/pull/83 just landed introducing `.binder`. Before we get too far disseminating that, from the points you have brought up, it may be more appropriate for it to be a non-hidden `binder` directory, instead of a hidden `.binder`. CI precedents are inconsistent on this - .travis is hidden, circle and appveyor are not.

The reproducible-environments goal we have here might nudge it in the direction of not being hidden (why hide your environment?). I'm about 51% in favor of using a visible directory, so happy to go with whatever others prefer. I can also see users wanting to hide the clutter of an implementation detail.

cc @willingc

**Comment by choldgraf** [comment]
I'm +1 on keeping the environment exposed as a non-hidden folder. I can see good reasons for either but I think you bring up a good point about transparency. The main complaint I could see people giving is that they want a folder called `binder` for other purposes...but this can't be *that* common

**Comment by minrk** [comment]
We could have a *file* called `.binder_dir_name` that sets the directory name... :)

**Comment by minrk** [comment]
https://github.com/jupyter/repo2docker/pull/86 makes it visible
