### ISSUE TITLE
CKAN activity tests are failing

### ISSUE THREAD

**Issue by manics** [jupyterhub/binderhub#1886]
### Bug description

https://github.com/jupyterhub/binderhub/blob/e14ef9d7bf51fe77449942b1b757c72d8b4321d2/binderhub/tests/test_repoproviders.py#L224
references https://demo.datashades.com/dataset/chart-test?activity_id=061888e9-e3c2-4769-b097-9c195a841e2f which currently returns a 404 error

https://demo.datashades.com/dataset/chart-test is valid, but the activity tab leads to https://demo.datashades.com/dataset/activity/chart-test which is empty

Support for CKAN was added in https://github.com/jupyterhub/binderhub/pull/1833
@u10313335 do you know if this is an expected change to the demo server?

**Comment by u10313335** [comment]
Thanks @manics for reporting this issue.
It seems that the site has been reset but I don't know the reason.

I'll change the demo server to a more stable one ASAP.

**Comment by manics** [comment]
Thanks! It looks like https://demo.ckan.org/dataset/activity/sample-dataset-1 has an activity stream now- maybe it's been enabled since the original PR?

**Comment by u10313335** [comment]
@manics The dataset on the https://demo.ckan.org should be an ideal one. However, the site will also be reset every several months AFAIK, which leads to failed tests due to different versions. Since actually there are few sites enabling activities, I think we can use the [depositar](https://data.depositar.io/en/about), a CKAN site maintained by our team and stable in the foreseeable future. I have submitted a PR for the changes.
