### ISSUE TITLE
Suggestion: add markdown rendering for readthedocs

### ISSUE THREAD

**Issue by ctb** [jupyterhub/binderhub#210]
See https://github.com/dib-lab/sourmash/blob/master/doc/conf.py#L295 for an example of using in this in our project.

You will also need to install the `recommonmark` package.

**Comment by choldgraf** [comment]
is this cuz you wanna make doc contributions, but only if it's in `.md`? :-)

**Comment by ctb** [comment]
You're right, I think the suggestion deserves some context!

I first starting using Markdown in earnest with both GitHub and Jupyter (then IPython) Notebook; neither supported ReST natively, but had good integrated Markdown support.  This was back in 2011 and 2012. However, at the time I was writing lots of tutorials and documentation in Sphinx sites, for which Markdown wasn't supported; and Sphinx had much superior Web site structure and version support, and readthedocs was a much superior hosting site for documentation over github. So for several years I had to split my markup language skills between the two.

During that time it became clear that Markdown was a simpler language for people to learn, and between the widespread adoption of both GitHub and Jupyter Notebook, many people became quite familiar with it. In particular, my labmates and collaborators all knew Markdown and struggled with ReST.  I was sad.

Then in about 2015 I discovered the recommonmark plugin for Sphinx and could realize the dream of having a largely unified writing environment. I also found Atom and its Markdown live preview to be pretty awesome.  But life still wasn't perfect because I didn't have a collaborative Markdown editing environment.

That changed in 2017 with the discovery of hackmd.io, which @luizirber introduced me to. Now I can have it all! I can write Markdown in a nice collaborative way online, I can edit and visualize it locally in Atom, I can save it to GitHub, and I can even copy-paste it to and from Jupyter Notebook!  I've converted several sites over to being Markdown based inside of Sphinx, which needs only a single shim - a toc or index file in reST - to do the proper site aggregation.

Imagine my surprise when I discovered that the Jupyter developer team, working via GitHub, was still using reST documents! Hence this suggestion.

I hope that provides adequate context for this issue and that you will consider my suggestion.

**Comment by choldgraf** [comment]
first, this is a great story, thanks for making it entertaining haha

second, I agree w/ you totally that markdown is way more human-readable and most people have familiarity with it because of github

that said, we use things like `.. warn::` and `.. note::` extensively in the jupyterhub world (at least in binderhub + z2jh). That said there I think there is a plugin for recommonmark to include sphinx directives with recommonmark. We're actually already using it in z2jh here: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/doc/source/reference.txt to render the schema page (it's a hacky solution though).

So in sum, I am intrigued at the possibility for its user friendliness, though a bit concerned at the potential for clunkiness and the work it'd require to transfer all the docs to MD. curious to hear what @willingc @yuvipanda @minrk @Carreau think

**Comment by ctb** [comment]
:)

There is no need to switch completely to markdown; see PR.  You can have both.

**Comment by Carreau** [comment]
I would prefer to have a single language in the documentation switching can be quite burdensome.

One of the reason we use markdown in notebook is because of client-side rendering; but the extensibility of rst is deeply missing. With enough funding and manpower we would likely create a blend of RST/markdown... but that's not the priority.

**Comment by choldgraf** [comment]
Though as a point of information, you can include `rST` with markdown:

http://recommonmark.readthedocs.io/en/latest/auto_structify.html#embed-restructuredtext

**Comment by willingc** [comment]
Many of the Jupyter documentation projects use a combination of rst, md, and ipynb. While md can be handy and is readable, rst is much more powerful for linking between docs and formatting with directives. That said, I'm totally cool with supporting any combination of the 3 formats. I would ask that rst be used unless creating a completely new document and do not know rst. Please do not mix rst and md in the same file as it's problematic once third party extensions are used.

Here are a few more resources on using both: 
[minimal doc structure for rst and md](https://github.com/willingc/doc-basics/blob/master/docs/source/conf.py) and [notebook with sphinx basics](
https://github.com/willingc/2017_09_28_sdpug_sphinx/blob/master/practical-sphinx.ipynb)

**Comment by yuvipanda** [comment]
Thank you everyone for your thoughtful comments, and to @ctb for starting it.

I personally find rst too complex, and have very little experience with it (these two are probably not unrelated!). I wish all docs were in markdown :)

However, since @willingc and @choldgraf have been the people dealing with docs the most and have much more experience in this than I do, I'm going to defer to them!

**Comment by willingc** [comment]
I think it's perfectly acceptable for those that are comfortable with markdown to use it to write new docs. Over time, if needed, they can be migrated to rst if needed.

I'm -1 on only using markdown since there are a number of niceties that one only gets with rst and sphinx.

**Comment by choldgraf** [comment]
@willingc I'm curious what problems you've run into when embedding rst into markdown files using recommonmark.  To my knowledge all recommonmark does is convert the markdown to rst, so that shouldn't create problems with embedded rst, no? I could be wrong in my assumptions tho.

Either way, I am OK with a  mixture if that's what works for people!

**Comment by ctb** [comment]
This is a great discussion, thanks for all the links! I'm personally quite happy with ReST but kids these days...
