### ISSUE TITLE
Check if binder instance is still running

### ISSUE THREAD

**Issue by navoshta** [jupyterhub/binderhub#287]
I wonder if there is an API to check if Binder instance is still running? In general, how long does it live before it gets deleted? Is it deleted after some period of inactivity, or by a timeout? 

Also, is there a way to check if repo needs rebuilding, even though server built previously is still running?

The background is: we are using Binder text-stream API directly in our mobile app (available at `https://mybinder.org/build/gh/...`). We also "cache" repo Binder URLs for some period of time to avoid generating similar instances when opening notebooks from the same repo. Ideally we would like to know if any particular instance is not running anymore, and we need to request another one; as well as if repo has changed and we need to ask to rebuild it.

**Comment by choldgraf** [comment]
That's a great question - I wonder if @minrk has thought about this at all in the context of Thebelab? 

Right now, this API doesn't exist to my knowledge, but I could see this being useful in order to avoid unnecessary kubernetes re-building of pods etc.

**Comment by minrk** [comment]
The best check I can think of right now is to hit the notebook's status API URL (hub.mybinder.org/user/xyz/api/status). If the binder is still running, you will get a JSON report. If it is not, you will get a 403 error (after a redirect to /hub/login).

**Comment by navoshta** [comment]
@minrk Thanks, I think we could use that.

So, what's the policy for stopping and deleting servers? Is it done after a timeout, or after some period of inactivity?

**Comment by yuvipanda** [comment]
@navoshta it's currently done after ten minutes of inactivity on the public mybinder.org instance (you can see the config [here](https://github.com/jupyterhub/mybinder.org-deploy/blob/staging/mybinder/values.yaml#L21)). 

There isn't really a way to check if a repo needs building. Is this an API we would want to add, @minrk? I feel like we can never guarantee that something that is 'built' will last forever. We might have to rebuilt it at any time for any number of reasons - new repo2docker version, we deleted all our images because we moved cloud providers, etc. The 'built' status is only a cache that end users should not rely on...

So if you use the text-stream API you'll already rebuild if needed. Don't need an explicit API for it I think?

as to seeing if a given user instance is still running, you could also make an API request to the notebook URL you got back. It should 404 if it is dead.

@minrk can you make a call to the Hub API without being authenticated? I thought you needed the Hub token for it.

Excited to see your work, @navoshta!

**Comment by minrk** [comment]
> So, what's the policy for stopping and deleting servers? 

It's a timeout of inactivity, usually about ten minutes, but configurable for the Binder deployment.

> can you make a call to the Hub API without being authenticated?

You can't make Hub API requests, but this is a direct request to the notebook's own API, authenticated with the token you already have from launching the instance earlier.

**Comment by navoshta** [comment]
Thanks @minrk and @yuvipanda! 

> So if you use the text-stream API you'll already rebuild if needed. Don't need an explicit API for it I think?

You're probably right, I think we're good with what Binder already offers.

> As to seeing if a given user instance is still running, you could also make an API request to the notebook URL you got back. It should 404 if it is dead.

Makes sense. I was probably overthinking it a bit; we will either simply try to load it and resort to re-requesting an instance, or use `.../api/status`.

We have already added [demo notebooks](https://juno.sh/juno-v-1-0-6-beta/) that use a server spawned with mybinder.org in latest beta release of Juno — works great so far, thanks! We are also planning to integrate mybinder.org support for arbitrary repos in the next few releases.
