### ISSUE TITLE
How to handle a user that clicks multiple binder links for the same repo

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#327]
I realized that we may be creating a problem for ourselves with the upcoming sphinx-gallery PR. That patch will add a Binder link to any example created by sphinx-gallery. However, that means that we'll probably start getting a lot of users that click one link, then go to another page in the docs and click another link.

To my knowledge, each time the same user clicks a link, a new user pod would be created. This seems sub-optimal if the person is really just clicking a bunch of links that point to the same base repository (AKA, they're just changing `filepath` in the URL).

What's a good way to handle these kinds of situations? I don't think it's a huge problem right now, but just trying to think about it ahead of time before it becomes an issue.

**Comment by minrk** [comment]
One option would be to set/update a cookie when a user launches a Binder. Then, when a user requests to launch a given binder, we check:

1. do they have this cookie set
2. if so, does it correspond to the same buildspec they are requesting now
3. if so, is it still running
4. if so, skip launch and redirect to running instance

Requirements for the cookie(s):

- must include running URL and buildspec
- must be able to store several values for different Binders (in general, this may require multiple cookies due to max cookie size)
- might want to also include Hub user name itself, to avoid possible escape confusion
- probably want to include the launch *token* to ensure that clearing other cookies in the meantime doesn't cause 403

This could all be server-side state

**Comment by Carreau** [comment]
@minrk description was close to what I would have said. I would also include an expiration timestamp for quick processing of anything that would be more than X-hours old.

I had a question by [peter Norvig](https://github.com/norvig/pytudes/commit/b59cc364fafa37bdbb1a0dea08f26ae71db3fd01#commitcomment-26031270) to add a badge/file, which typically would trigger this kind of issues.

One other thing wee need to be careful of is multiple tabs open on the same systems might be confusing.

**Comment by manics** [comment]
See https://github.com/jupyterhub/binderhub/issues/425
