### ISSUE TITLE
Consider *not* launching automatically

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#350]
Here's a quick thought:

A lot of users have asked if they can see the logs for an already-built repository. Eventually I think it'd be good to store these somewhere that people can reference. However, in the meantime what if we added an extra step when a user hits "launch" on a repository that hasn't been built yet. That'd give them time to scan the logs. So what I'm thinking is:

* The "launch" button would now be called "build"
* If a user hits a binder URL directly (e.g. with `v2/gh/etc`) then it'll launch automatically.
* If a user hits "build" with a repo that's already built, it'll launch automatically.
* If a user hits "build" with a repo that hasn't been built, it'll build and the button would change color (maybe to red?) and be called "launch". Then the user would need to hit that button to start the redirect process.

Thoughts on this? I think it could be a good way to easy some binder repo author frustration without changing the experience for users that are just clicking binder links.

**Comment by yuvipanda** [comment]
My preference would instead be to solve the individual problems that are ocurring rather than provide a 'build' step that doesn't actually exist. This would involve:

1. Different experience for users who are just clicking binder links (https://github.com/jupyterhub/binderhub/issues/271), to show them stuff is happening. This allows for a totally different UX than what needs to be present on mybinder.org, and is a very useful change to happen.
2. Understand *why* users want to see logs of built images, and provide ways to solve these problems. We already show logs of failed builds, but what we consider 'failed' is fairly limited. If it isn't doing something the user wants but still 'succeeds' to build an image, that's frustrating that the logs are now gone. It looks like we pretty much have to have some amount of medium-term storage of build logs (and some UX to show these to people) to fix this problem. I'd rather we tackled that.

From a UX perspective, I'd like us to not introduce the word 'build' as an action that the user can do explicitly different from 'launch'. Separating the user's mental model from what we're actually doing will only cause more confusion, not less. We should solve the underlying issues IMO, than apply possible bandaids, esp. if bandaids change user mental models of how stuff works.

A quick fix now would perhaps to be have a checkbox (ticked by default) under the launch button that is something along the lines of 'redirect to notebook when ready' that users can uncheck to wait and watch logs. There is consensus for this when this topic came up in https://github.com/jupyterhub/binderhub/issues/196 I think.

**Comment by choldgraf** [comment]
that's a fair point - I think some kind of checkbox would be a good solution. I'm gonna close this in lieu of discussion in #196 either way
