### ISSUE TITLE
Document banning ? 

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#373]
I saw that we recently merged in a patch to allow banning of certain repositories. Did this get documented yet? If not, I think we should A. Make it clear what would get you banned on mybinder.org, and B. Tell people how to do the same for their own binderhubs.

**Comment by willingc** [comment]
@choldgraf let's open an issue for Part A on mybinder.org-deploy since that is a policy decision for the service. Based on yesterday, it was a repo that overloaded the site and looked like there was an issue with the particular repo.

As for Part B, it's currently documented here (https://binderhub.readthedocs.io/en/latest/reference/repoproviders.html#repoproviders). For now, I think the config setting documentation is sufficient in the short term. I'm not sure we should provide any policy guidance, beyond documenting the setting.

Let's close this as resolved here and open Part A on mybinder.org-deploy.

**Comment by choldgraf** [comment]
sounds good

new issue: https://github.com/jupyterhub/mybinder.org-deploy/issues/240
