### ISSUE TITLE
Update install instructions for latest dev version

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#402]
Over the last few months we've made some changes to the dev version of the BinderHub helm chart such that the instructions will no longer work. I spent a bit of time today figuring out how to update these instructions so that people can use the latest version. Here's a summary of things I found...

can somebody take a look and make sure they look generally correct, then I'll make a PR:

* add `--cluster-version=1.8.4-gke.1` to the gcloud command to create a cluster
* Add command to make yourself admin `kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=<my-email>`
* Add commands to give the tiller admin priveleges:
  ```
  kubectl --namespace kube-system create sa tiller
  kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
  helm init --service-account tiller
  ```
* Give the binder pod the ability to create new pods: `kubectl create clusterrolebinding binderhub --clusterrole cluster-admin --serviceaccount=bhub-test:default` **NOTE: this is unsafe so we should figure out a better command**

**Comment by yuvipanda** [comment]
Thanks for taking the time to figure it out, @choldgraf!

https://www.youtube.com/watch?v=Nw1ymxcLIDI is a good intro to RBAC rules that was recommended to me by others who found it useful to understand the issues. Might be useful for others too.

I want to note that we ship our own rbac rules in the helm chart (https://github.com/jupyterhub/binderhub/blob/master/helm-chart/binderhub/templates/rbac.yaml, and similar for z2jh) that should mean manually creating clusterroles for anything related to binderhub should be unnecessary (and dangerous). If just setting up RBAC properly with helm does not work, that is a bug in the charts we should debug & fix rather than provide people with possibly dangerous kubectl commands to run. The RBAC rules we have *do* work in our staging and prod clusters, so perhaps playing with those to find out why it works there but not in clusters users create would be useful.

**Comment by choldgraf** [comment]
Just a note that the original error that I got (which was fixed by the RBAC command) was this:

```
    HTTP response headers: HTTPHeaderDict({'Audit-Id': 'e00358d1-4ab5-4461-8aa8-04cc3b6ae0a4', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Fri, 05 Jan 2018 19:53:15 GMT', 'Content-Length': '315'})
    HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:serviceaccount:bhub-test:default\" cannot create pods in the namespace \"bhub-test\": Unknown user \"system:serviceaccount:bhub-test:default\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}
```

it seems like there's a role defined here that should be able to create pods:

https://github.com/jupyterhub/binderhub/blob/b699732258cdaf941b008476b5dc39476bd2b9cd/helm-chart/binderhub/templates/rbac.yaml#L9

but the error message makes it seem like that role is not being used:

`"message":"pods is forbidden: User \"system:serviceaccount:bhub-test:default\" cannot create pods in the namespace \"bhub-test\": Unknown user \"system:serviceaccount:bhub-test:default\"`

**Comment by choldgraf** [comment]
Gave this another shot using the latest z2jh docs and bhub and it worked! Not sure what was happening with RBAC before, but I had no issues this time. I added a PR to update the docs and to prevent further z2jh / bhub drift here:

https://github.com/jupyterhub/binderhub/pull/418
