### ISSUE TITLE
Stale pods not getting culled

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#450]
I've noticed that we often have pods that are quite old, but not culled. E.g.:

```
jupyter-jakevdp-2dpythond-2dsciencehandbook-2d5uc7hu0e            1/1       Running           0          4d
jupyter-uhd-2dpap-2dcourse-2ddeploy-2d1phqnvt9                    1/1       Running           0          4d
jupyter-brian-2dteam-2dbrian2-2dbinder-2dee0ln2jl                 1/1       Running           0          4d
```
It seems there might be a bug in our culling process...this issue is here to make sure we remember to follow up on this

**Comment by choldgraf** [comment]
@mpacer @Carreau this is the culling issue - note that the fix will probably be something in JupyterHub

**Comment by yuvipanda** [comment]
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/master/images/hub/cull_idle_servers.py is the code. Restarting the hub process seems to get this to wake up and fix things, so I dunno what's going on.

**Comment by yuvipanda** [comment]
![image](https://user-images.githubusercontent.com/30430/36570790-9254ce74-17e8-11e8-8e21-19ad05a9685e.png)

You can look at the effects when the culler is working after a hub restart.

**Comment by yuvipanda** [comment]
@choldgraf had a hypothesis for the sawtooth pattern but unsure what that is.

**Comment by betatim** [comment]
Some changes to the culler to make it better at dealing with slow to stop users https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/531

**Comment by minrk** [comment]
sawtooth pattern makes sense since culling should only happen every 10 minutes, so there should be six teeth an hour if everything is behaving as intended.

I've been thinking about the big drop in running pods, and I think it has to do with the culler hitting 400 errors fixed in jupyterhub/zero-to-jupyterhub-k8s#531 and that resulting in a disruption of the culler, effectively preventing culls after the first failure from taking place.

A normal cull sequence in the logs will look like:

```
[I 180226 13:11:03 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-26 12:51:33.653000)
[I 2018-02-26 13:11:03.635 JupyterHub proxy:254] Removing user $user from proxy (/user/$user/)
[I 2018-02-26 13:11:08.760 JupyterHub base:548] User $user server took 5.122 seconds to stop
[I 180226 13:11:08 cull_idle_servers:83] Culling user $user (inactive since 2018-02-26 12:51:33.653000)
[I 2018-02-26 13:11:08.765 JupyterHub log:122] 204 DELETE /hub/api/users/$user/server (cull-idle@127.0.0.1) 5130.19ms
[I 2018-02-26 13:11:23.354 JupyterHub log:122] 204 DELETE /hub/api/users/$user (cull-idle@127.0.0.1) 19.10ms
```

Note that the culler logs that it's *going to* cull the server, then there's a log from the Hub when each API request completes. Here are [some logs](https://console.cloud.google.com/logs/viewer?project=binder-prod&minLogLevel=0&expandAll=false&timestamp=2018-02-22T23:37:12.000000000Z&interval=JUMP_TO_TIME&resource=container%2Fcluster_name%2Fprod-a&logName=projects%2Fbinder-prod%2Flogs%2Fhub-container&filters=text:gbnl0a5h) from the above window:

```
[I 2018-02-22 21:58:39.780 JupyterHub log:122] 201 POST /hub/api/users/$user (binder@10.12.5.222) 64.81ms
[I 2018-02-22 21:58:44.321 JupyterHub base:447] User $user took 4.525 seconds to start
[I 2018-02-22 21:58:44.323 JupyterHub proxy:231] Adding user $user to proxy /user/$user/ => http://10.12.7.247:8888
[I 2018-02-22 21:58:44.337 JupyterHub log:122] 201 POST /hub/api/users/$user/server (binder@10.12.5.222) 4546.81ms
[I 180222 22:15:44 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 22:25:43 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 22:35:44 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 22:45:43 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 22:55:43 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 23:05:44 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
<hub restarts here as part of a deploy>
[I 2018-02-22 23:09:42.095 JupyterHub app:1223] $user still running
[I 180222 23:09:45 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 23:10:15 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 23:10:46 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 23:11:15 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 23:11:46 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 23:12:16 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 23:12:46 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 23:13:16 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 23:13:46 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 23:14:16 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 23:14:46 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 23:15:16 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 23:15:46 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 23:16:16 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 23:16:46 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 180222 23:17:16 cull_idle_servers:68] Culling server for $user (inactive since 2018-02-22 22:00:59.611000)
[I 2018-02-22 23:17:27.295 JupyterHub proxy:254] Removing user $user from proxy (/user/$user/)
[W 2018-02-22 23:17:37.300 JupyterHub base:556] User $user: server is slow to stop
[I 2018-02-22 23:17:37.304 JupyterHub log:122] 202 DELETE /hub/api/users/$user/server (cull-idle@127.0.0.1) 10023.01ms
[I 180222 23:17:46 cull_idle_servers:75] Culling user $user (inactive since 2018-02-22 22:00:59.611000)
[W 2018-02-22 23:17:46.777 JupyterHub web:1588] 400 DELETE /hub/api/users/$user (127.0.0.1): $user's server is in the process of stopping, please wait.
[W 2018-02-22 23:17:46.779 JupyterHub log:122] 400 DELETE /hub/api/users/$user (cull-idle@127.0.0.1) 4.55ms
[I 2018-02-22 23:17:57.535 JupyterHub base:548] User $user server took 30.239 seconds to stop
[I 180222 23:37:11 cull_idle_servers:75] Culling user $user (inactive since 2018-02-22 23:17:57.489184)
[I 2018-02-22 23:37:12.190 JupyterHub log:122] 204 DELETE /hub/api/users/$user (cull-idle@127.0.0.1) 22.07ms
 ```

Note how the culler repeatedly logs that it's going to cull the user, but the Hub never logs an HTTP request.

The logs also show that there are loads of timeout errors that we aren't seeing:

```
[E 180222 23:05:44 concurrent:344] Future <tornado.concurrent.Future object at 0x7f0790606a90>
exception was never retrieved: Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
File "/usr/local/bin/cull_idle_servers.py", line 73, in cull_one
    yield client.fetch(req)
File "/usr/local/lib/python3.6/dist-packages/tornado/gen.py", line 1055, in run
    value = future.result() 
File "/usr/local/lib/python3.6/dist-packages/tornado/concurrent.py", line 238, in result 
    raise_exc_info(self._exc_info) 
File "<string>", line 4, in raise_exc_info
    tornado.httpclient.HTTPError: HTTP 599: Timeout in request queue
```

meaning that cull requests are being aborted for taking too long to get into the queue. I opened [this PR](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/540) to ensure that all requests are awaited rather than stopping at the first failure, which should have fixed the failure to *request* cull after some culls fail to complete.

It's still unclear exactly what allowed the culling to proceed past the blockage (it could have been a totally coincidental change in dictionary ordering caused by the Hub restart, or a more serious bug in jupyterhub/kubespawner state that required a restart), but the recent changes to the culler (avoid errors by noticing when servers are slow to stop and ensure we try every user even when some requests fail) should greatly improve things.

This also means that until recently, when some servers are slow to stop we could have been running at much higher load than we needed to because potentially many servers were idle and not being culled.

**Comment by choldgraf** [comment]
I believe that I saw a bunch of culling-related PRs in the last day or two...what is a metric we can use to decide if "culling has been fixed" (at least to a reasonable level)?

**Comment by choldgraf** [comment]
I think that culling has been fixed, as pod ages are now pretty much always capped and properly culled
