### ISSUE TITLE
Accessing C-based Python bindings

### ISSUE THREAD

**Issue by jan-janssen** [jupyterhub/binderhub#511]
Hello, 

I created a short jupyter notebook to demonstrate the Lammps molecular dynamics code http://lammps.sandia.gov: 
https://github.com/jan-janssen/lammps-notebooks/tree/master 

I am able to execute the simulation code, but when I try to receive the results I get: 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-2f9e76cb1d69> in <module>()
----> 1 L.run(10)

/srv/conda/lib/python3.6/site-packages/lammps.py in run(self, *args, **kwargs)
    727   def run(self, *args, **kwargs):
    728     output = self.__getattr__('run')(*args, **kwargs)
--> 729     self.runs += get_thermo_data(output)
    730     return output
    731 

/srv/conda/lib/python3.6/site-packages/lammps.py in get_thermo_data(output)
    656     current_run = {}
    657 
--> 658     for line in lines:
    659         if line.startswith("Per MPI rank memory allocation"):
    660             in_run = True

TypeError: 'NoneType' object is not iterable
```

While the same code and versions are running fine on my personal docker instances. Therefore I am wondering if you are restricting the access in some way? 

Best, 

Jan

**Comment by minrk** [comment]
Looking at the code, there is a bug in lammps because `output` [can be None](https://github.com/lammps/lammps/blob/8e3ba36a4f24c91b6967ed4fa7f515f3a68a11ef/python/lammps.py#L1030), but `get_thermo_data` [assumes](https://github.com/lammps/lammps/blob/8e3ba36a4f24c91b6967ed4fa7f515f3a68a11ef/python/lammps.py#L754) that `output` is a string or list of strings.

Exactly *why* this is is not clear to me. How does the lammps output capture work?

**Comment by jan-janssen** [comment]
As far as I understand it is accessing the output directly using Python CTypes bindings and the same is working for me in a regular Docker container - on my local machine, but it is not working on https://mybinder.org - so I have the feeling the access is somehow blocked.
