### ISSUE TITLE
Feature request: add a config option to not rebuild for every file changes in the repo

### ISSUE THREAD

**Issue by aborruso** [jupyterhub/binderhub#556]
Hi,
it would be fanstatic to have as option some flag, that force the rebuild only when you change something inside the `binder` folder of the repo.

Thank you

**Comment by betatim** [comment]
I think the approach of having one "stable" repo that is rebuilt rarely (and expensive to build) and then another one that changes frequently is what we should recommend to people. An example is the binder setup for https://github.com/Calysto/conx.

I'd be -1 on having certain files excluded from triggering a rebauild. Both from a technical point of view (we would need smarter code for "needs rebuilding?") and because users would end up with a binder that doesn't contain what they just saw on GitHub.
