### ISSUE TITLE
Software depending on correctly set system environment variables

### ISSUE THREAD

**Issue by iskreng** [jupyterhub/binderhub#575]
Hello,

I am trying to run my ipython notebook which relies on having IRAF installed. I did include in my github repository apt.txt file which contains iraf to be installed and also an environment.yml file with my local environment dependencies. Seemingly all went well when I launched it in mybinder.org, however, when I run the first cell in my notebook I get the error that I attach as a screenshot at the end. I don't care so mych about graphical interaction, but I'm concerned that the IRAF installation is not found.
I will appreciate your help on how can I resolve this. 

My repository is located here:
https://github.com/iskreng/test
And this is mybinder launch link:
https://mybinder.org/v2/gh/iskreng/test/master?filepath=READMEpy.ipynb

Many thanks!
Iskren

![mybinder](https://user-images.githubusercontent.com/8777015/40489716-06034e2c-5f6a-11e8-8629-e8be3387f2f5.png)

**Comment by betatim** [comment]
Binder currently does not support setting environment variables via a configuration file.

This means that unfortunately you will have to set `iraf` and `IRAFARCH` at the top of your notebook.

I am not familiar with PyRaf and iraf. It looks like they provide conda packages (which you use), can conda packages set environment variables as part of being installed?

Another thing to try is to edit `$PREFIX/etc/conda/activate.d` from the [`postBuild` script](http://repo2docker.readthedocs.io/en/latest/samples.html#system-post-build-scripts) in your repository. This is a bit more involved/tricky because it involves knowledge of repo2docker and conda etc. I think you can add something like  `echo HELLO=world > /srv/conda/etc/conda/activate.d` to your `postBuild` and that should set the `HELLO` environment variable when you launch your repository on mybinder.org. If that works you could then try and work out what value your raf related variables should be set to.

**Comment by betatim** [comment]
This is the documentation for `activate.d` https://conda.io/docs/user-guide/tasks/manage-environments.html#macos-and-linux Mistake number one in my comment is that activate.d should be a directory, not a file.

**Comment by iskreng** [comment]
Yes, normally even if I don't have a local/separate/independent iraf installation, conda is installing it from the astroconda channel (as you correctly noted) and then it should properly set the paths to point to the location where iraf is installed in the conda tree, i.e. at /path/to/miniconda/pkgs/iraf*

That is, iraf should be installed and "seen" by the python and pyraf on mybinder. Btw, pyraf is just a python wrapper for iraf (http://iraf.noao.deu).

If the above is not helpful to narrow down the issue, then I'll try your suggestions.

**Comment by betatim** [comment]
The name of your conda environment is ignored, the contents of `environment.yml` is installed into the root conda environment on mybinder.org

`setenv` is not a notebook command (I think it is a csh command) that is why it does not exist. You need to use Python's `os` module to set environment variables from Python.

I'd recommend to get someone from Pyraf or iraf to help you with this as we know nothing about iraf, pyraf, etc

**Comment by iskreng** [comment]
Thank you, I will do so.
