### ISSUE TITLE
'apiToken's in secret.yaml

### ISSUE THREAD

**Issue by bitnik** [jupyterhub/binderhub#592]
[In the documentation](https://binderhub.readthedocs.io/en/latest/setup-binderhub.html#create-secret-yaml-file) there are `jupyterhub.hub.services.binder.apiToken` and `hub.services.binder.apiToken` in `secret.yaml` and they have the same value. First one is passed to JupyterHub secret config and also used in [binder's secret](https://github.com/jupyterhub/binderhub/blob/master/helm-chart/binderhub/templates/secret.yaml#L10). Is second one used anywhere? Do I miss sth?

**Comment by bitnik** [comment]
okay, actually second one must passed to `binder.hub-token` in [binder's secret.yaml](https://github.com/jupyterhub/binderhub/blob/master/helm-chart/binderhub/templates/secret.yaml#L10). I mean, instead of
```yaml
  binder.hub-token: {{ .Values.jupyterhub.hub.services.binder.apiToken | b64enc | quote }}
```
there should be
```yaml
  binder.hub-token: {{ .Values.hub.services.binder.apiToken | b64enc | quote }}
```
and then binder and JupyterHub are more clearly separated in heml chart.

And also I think in [secret.yaml](https://binderhub.readthedocs.io/en/latest/setup-binderhub.html#create-secret-yaml-file) it is better to have 
```yaml
hub:
  apiToken:
```
instead of
```yaml
hub:
  services:
    binder:
      apiToken:
```
Then it is more clear that binder uses `hub.apiToken` to communicate with  JupyterHub (`hub.url`). 

If you agree, I can do the PR. What do you think?

**Comment by betatim** [comment]
Not sure why the structure of `hub.services.binder.apiToken` is mirrored from the JupyterHub structure (where it makes sense because JHub sees BHub as a service).

I would say in https://github.com/jupyterhub/binderhub/blob/master/helm-chart/binderhub/templates/secret.yaml#L10 you do want to use the token from JHub, because Bhub is a service for JHub.

Like you I can't quickly find where the second definition of `hub.services.binder.apiToken` is used in the chart. Have you tried removing it to see what happens?

**Comment by bitnik** [comment]
Yes, I tried it and it works without error. I think `hub.services.binder.apiToken` is not used anywhere.

Actually in https://github.com/jupyterhub/binderhub/blob/master/helm-chart/binderhub/templates/secret.yaml#L10, it is not important if `jupyterhub.hub.services.binder.apiToken` or `hub.services.binder.apiToken` is used. Because even BinderHub is a service for JupyterHub they use the same conf file (because BinderHub chart requires JupyterHub chart) and one definition of token is enough. But as far as I understand JupyterHub and its externally managed service normally have 2 different deployments and each has a token with same value (probably that's why you wanted to have two `apiToken`s in secret.yaml). 

In the previous message my suggestion was to make a clear separation between configurations of JupyterHub and its service (BinderHub). That means, anything set under `jupyterhub:` in conf.yaml or secret.yaml configures only JupyterHub.

I know this is actually not important. I was just confused when I started to try running BinderHub as a service under `/services/binder` by using JupyterHub and BinderHub charts separately.

**Comment by minrk** [comment]
Yes, the `hub.services` copy of `jupyterhub.hub.services...` is not used. There is a single value at `jupyterhub.hub.services.apiToken` that is used both by the Hub deployment (to grant access for this token) and Binder deployment (to access the Hub). I think initially, we didn't figure out how to get a value that would be used in both charts, but we've since figured out how to use a single value.

The structure of the config *must* be `jupyterhub.hub.services.binder.apiToken`, because that's how the jupyterhub chart registers API tokens that may be used. We cannot use `hub.apiToken` because API tokens in jupyterhub must be associated with a service account. The structure is dictated by the jupyterhub chart and cannot be changed in the binderhub chart. The jupyterhub chart doesn't see the top-level `hub` values.

It would indeed be nicer to have `hub.apiToken` for users, but we would need to make sure that this is copied to `jupyterhub.hub.services.binder.apiToken`, which I'm not sure is possible. If you figure it out, I would love to know how!

**Comment by betatim** [comment]
We could update the docs and remove the spurious `hub.services.binder.apiToken` though. Would be a good PR while we figure out the rest.

**Comment by bitnik** [comment]
I was actually suggesting to have 2 apiTokens in config: `hub.apiToken` and `jupyterhub.hub.services.binder.apiToken` to be filled with same value. But I see that `jupyterhub.hub.services.binder.apiToken` is enough to configure both charts and the other one is redundant. I will make a PR to update the docs.

@minrk I couldn't find a way to copy values from parent chart to child chart.There is a related [PR](https://github.com/kubernetes/helm/pull/3243) to export values from parent to child chart, but it is closed now.
