### ISSUE TITLE
Increase bandwidth for notebook data transfer

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#61]
This will be particularly useful for more data-heavy interactive stuff in the notebook, e.g. ipywidgets. I think this is the relevant config parameter:

`c.NotebookApp.iopub_data_rate_limit`

**Comment by yuvipanda** [comment]
@minrk @Carreau can you tell us if increasing this by default in binder will cause negative side effects elsewhere?

**Comment by minrk** [comment]
Widgets shouldn't have an issue in notebook 5.1 due to https://github.com/jupyter/notebook/pull/2293 . There isn't a value that both solves the issue (preventing large amounts of output from crashing the browser) and allows well-behaved large outputs to never hit the rate limit. Setting it to 0 (disabled) restores the pre-rate limit behavior, and may be the best for now.

**Comment by choldgraf** [comment]
personally, I am +1 on keeping the limit there, and exposing an easy way for users to change this if they wish (e.g. in the binderfile concept). In the future if we see this error popping up quite frequently (which we should be able to see in logs) then we can discuss removing or increasing the default limit. WDYT?

**Comment by choldgraf** [comment]
did we resolve this issue w/ bandwidth limits?

**Comment by willingc** [comment]
@minrk @yuvipanda @Carreau Following up on @choldgraf's question... Recommend closing unless there is an actionable next step on this.

**Comment by minrk** [comment]
Updating the notebook version to 5.1 ought to solve it for most.

**Comment by yuvipanda** [comment]
Going to close this as 'solved with 5.1' since nobody has complained since :D

**Comment by rcpeene** [comment]
What is the preferred way to adjust this setting with binder? I am running into this limit with data visualization. Best solution I can figure is to use a postBuild script to place a jupyter_notebook_config.py in home/.jupyter.

**Comment by minrk** [comment]
@rcpeene do you mean for your own BinderHub deployment? You can mount jupyter config files into `/etc/jupyter/` and override this setting. It's not really recommended to modify this value on a per-binder basis on mybinder.org, since the limit is there for a reason - when too much data flows through here, it can crash various components, including the browser and the notebook server.

A python package that drops a json data_file into `etc/jupyter/jupyter_notebook_config.d/something.json` can modify config by being installed in e.g. requirements.txt, without a postBuild.

**Comment by rcpeene** [comment]
Yes I am running it on mybinder.org. If adjusting the config is not the solution, how do I prevent my kernel from crashing when downloading a file for visualization?
