### ISSUE TITLE
Support for pointing to gists

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/binderhub#62]
Quicker than setting up an entire github repository!

**Comment by choldgraf** [comment]
Should this be in repo2docker?

**Comment by yuvipanda** [comment]
Nope - repo2docker only cares about getting a git repository. Since gists are already git repositories, we don't need any additional work in repo2docker.

**Comment by choldgraf** [comment]
gotcha - in that case, perhaps it seems like this is just a matter of making sure URLs to gists work + documenting for users how to do this...doesn't sound like we need to change any machinery in general, no?

What about the URL structure? I think gists follow the same username/gist-id convention so we could just treat `gist-id` as a repo name for url purposes...though gists don't have things like "branches". Alternatively we could have a separate spec for that (e.g. instead of `/v2/gh/` we have `/v2/gist`). WDYT?

**Comment by choldgraf** [comment]
will be closed by #306

**Comment by bitnik** [comment]
@choldgraf i think this issue should have been closed or ?
