### ISSUE TITLE
Python 3.5 compatibility

### ISSUE THREAD

**Issue by evertrol** [jupyterhub/binderhub#640]
I noticed `setup.py` only requires Python >= 3.5, but there are a lot of f-strings in the source code, which are a Python 3.6+ feature.

I guess this is largely circumvented by use of containers and helm charts using Python 3.6 (and similarly, avoid the problem in #639), but I thought I would put the note here anyway.

**Comment by choldgraf** [comment]
this is a good point - I'm guessing that we won't stop using f-strings so perhaps we should bump the requirements to 3.6...what do people think?

**Comment by betatim** [comment]
Sounds like a good first contribution.

Should we merge this with #639 as the issues are very related?

**Comment by willingc** [comment]
Let's keep the two issues/PRs separate for the moment.

At a quick glance, it looks like the f-strings are used in utilities (`imagecleaner.py`)  that are run in Docker containers and minikube testing not in the base binderhub code.

Currently, JupyterHub stable supports 3.5. As an FYI 3.5 does not go End of Life until 2020 [ref](https://devguide.python.org/#status-of-python-branches).

I don't have a strong feeling about dropping 3.5 on binderhub as it's a newer project. Yet, we should perhaps through linting that we are not introducing f-strings on other repos that still support 3.5.

@minrk Thoughts?

**Comment by minrk** [comment]
Since binderhub is ~always run in a container, bumping the required Python to 3.6 seems like the right thing to do. Since it's already been a requirement due to incompatibility with Python 3.5 and not an issue, bumping the declared requirement to match reality makes more sense to me than reverting the code to match a never-actually-true claim of support for 3.5.
