### ISSUE TITLE
Zero to BinderHub on One's Own Servers?

### ISSUE THREAD

**Issue by jzf2101** [jupyterhub/binderhub#733]
@aculich @choldgraf @cmd-ntrf @betatim @consideRatio 

Do we have recommendations on how to set up BinderHub on one's own servers? 

@elfeto and @alistairewj and I have been discussing setting up a BinderHub on their servers but our docs are only for GKE.

I've only deployed on GKE.

**Comment by choldgraf** [comment]
I think this will need contributions from the community to figure out - I haven't deployed a binderhub outside of GKE as well

**Comment by betatim** [comment]
Maybe this is a topic for discourse to get more eyes on it. We only offer support for GKE at the moment (https://binderhub.readthedocs.io/en/latest/create-cloud-resources.html#setting-up-kubernetes-on-google-cloud) largely because as a project we don't have access to anything else. This means that to add support for more "types" of kubernetes we need to grow the community of people who run hubs on other platforms than GKE.

**Comment by cmd-ntrf** [comment]
If the server is an instance on OpenStack, one could use what we presented for PEARC18, Terraform script for BinderHub.
https://github.com/etiennedub/terraform-binderhub

If we are talking about a baremetal server, we can cut the instance creation and call directly the binderhub install script : https://github.com/etiennedub/terraform-binderhub/blob/master/terraform-modules/binderhub/assets/install-binderhub.sh

**Comment by mathematicalmichael** [comment]
I rent a server from digitalocean and would love some guidance on how to set up binderhub on there.

**Comment by simonflood** [comment]
@mathematicalmichael I know it's been a few months since you asked but have you seen https://github.com/alan-turing-institute/the-turing-way/blob/master/workshops/build-a-binderhub/digital_ocean.md from The Turing Way?

**Comment by mathematicalmichael** [comment]
> @mathematicalmichael I know it's been a few months since you asked but have you seen https://github.com/alan-turing-institute/the-turing-way/blob/master/workshops/build-a-binderhub/digital_ocean.md from The Turing Way?

no! that's awesome. it is a kubernetes deployment, which isn't exactly what I was hoping for, but it certainly helps. i do realize that it is probably the best way to deploy the project. I'm just afraid of the costs...

**Comment by betatim** [comment]
BinderHub relies on Kubernetes, so you will need a kubernetes cluster to run it.

---

Hi there 👋!

Can we move (or restart with a more specific title?) this discussion to http://discourse.jupyter.org/ (where most of the people who hang out here also hang out, as well as more people). We are trying to streamline the [different discussion places](https://discourse.jupyter.org/t/a-proposal-for-jupyterhub-communications/505) and want to use the issues on GitHub repos for technical discussions on how to change the contents of the repo. More general discussions should go to discourse so that they are easier to find, better indexed by google and generally more accessible than being hidden in the bowls of a GitHub repository ;)

Thanks!

**Comment by manics** [comment]
Hi :wave: This is an old issue so I'm closing it. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
