### ISSUE TITLE
Rebuild image only if environment.yml changes

### ISSUE THREAD

**Issue by emarsden** [jupyterhub/binderhub#746]
Binderhub seems to be building a new image for each commit to the git repository. Given that image rebuilds are very expensive, and that notebooks are likely to be updated far more often than environment.yml / requirements.txt, it seems that it would be more efficient to rebuild an image only when there is a change to a hash of whatever elements repo2docker used to generate the image.

**Comment by betatim** [comment]
This behaviour is unlikely to change. The reason for this is that (for example) what happens if you install software according to a `requirements.txt` can depend on any other file in the repository. We are not aware of any good way of detecting the full chain of dependencies in an automatic way.

There are attempts to speed up builds in these issues: jupyter/repo2docker#461 jupyter/repo2docker#478 and jupyter/repo2docker#410.
