### ISSUE TITLE
A question about 3d interaction

### ISSUE THREAD

**Issue by LanceNorskog** [jupyterhub/binderhub#760]
Where is an example of a notebook that supports interactive 3d while rendered from mybinder.org?

**Comment by betatim** [comment]
I don't think we have a list, off the top of my head: https://github.com/maartenbreddels/ipyvolume

If you have a particular library in mind it is probably best to start asking in the forum for that library. If it can run in a notebook locally it should also work on mybinder.org.

**Comment by lheagy** [comment]
@banesullivan has done some really nice work for 3D viz with VTK. Bane, do you have a binder example with interactive 3D viz?

**Comment by banesullivan** [comment]
A long while back I tried to put [these examples](https://github.com/OpenGeoVis/PVGeo-Examples) on mybinder but had issues setting up VTK. Those examples are out of date and I haven't tried this in a while but I think it should be doable!

Heading out of town for a week but I'll try to get some [`vtki` examples](http://docs.vtki.org/en/latest/examples/index.html) on a mybinder.

**Comment by betatim** [comment]
Should we move this thread to http://discourse.jupyter.org/?

We recently decided that it would be a good idea/experiment to have discussion like these on discourse instead of GitHub. The hope is that it makes them easier to find (via google), more visible and increases the signal to noise of GitHub issues.

**Comment by banesullivan** [comment]
Status update: I've been successful with 3D rendering on Binder in the [OpenGeoVis/PVGeo-Examples](https://github.com/OpenGeoVis/PVGeo-Examples) repository.

Launch these notebooks on MyBinder: [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/OpenGeoVis/PVGeo-Examples/master)

Note that these notebooks are not currently interactive but I plan to make `vtki` interoperable with these features https://github.com/pyviz/panel/pull/312 in [pyviz/panel](https://github.com/pyviz/panel) to make 3D viz interactive directly in a notebook!

**Comment by betatim** [comment]
This looks nice @banesullivan! Definitely something to post on http://discourse.jupyter.org/

I'll close this issue now because we are trying to streamline the [different discussion places](https://discourse.jupyter.org/t/a-proposal-for-jupyterhub-communications/505) and want to use the issues on GitHub repos for technical discussions on how to change the contents of the repo. More general discussions should go to discourse so that they are easier to find, better indexed by google and generally more accessible than being hidden in the bowls of a GitHub repository ;)

Thanks!
