### ISSUE TITLE
Build logs sometimes failing to push to the UI

### ISSUE THREAD

**Issue by shibbas** [jupyterhub/binderhub#798]
Hi, 

I'm seeing an issue where the build logs don't seem to be populating in UI sometimes in my deployment of BinderHub, but they are still showing up in the kubernetes pod. The logs in the UI seem stuck at "Waiting on the build to start" step for a long time. There doesn't seem to be any errors related to this in the binder or build pods. 

Has anyone experienced this?

**Comment by betatim** [comment]
I can't think of the last time when I've seen this :-/

OTOH networking issues or the build pod watcher/reflector losing track of the build pods that are running is the reason for this.

Are you running `master` (or near to it) of binderhub?

**Comment by betatim** [comment]
Does the user eventually get redirected to their running pod or does it get stuck at "waiting for build pod to start"? If the latter happens that would point towards the pod reflector not working properly.

Just remembered that we did recently have a problem on mybinder.org where build logs wouldn't get streamed. This turned out to be some internal networking issue and "went away by itself". We first noticed it because `kubectl logs <podname>` had stopped working. It printed an error message about the kubernetes master not being able to create a ssh tunnel to the node.

https://github.com/jupyterhub/mybinder.org-deploy/blob/master/docs/source/incident-reports/2019-02-20-no-logs.md is the report on that

**Comment by shibbas** [comment]
Hi! Yes, i am using the latest development release helm chart: binderhub-0.2.0-64bb3c7. I believe it's sync'd to the latest master. 

Sometimes the build logs resume from the middle or after the code reaches the launcher. I've seen the launcher fail due to timeouts as well the first and second time after waiting 300 seconds to spawn a session. Other times, it gets stuck completely and i never see the user session launch. I have seen it working end to end correctly sometimes though. 

Thank you for the pointer, I was suspecting some issue with networking as well, I'll dig deeper into it. 
`kubectl logs <podname>`  do still work for me which is why this was confusing since I don't see any errors in the logs. Let me know if you have any other pointers!

**Comment by betatim** [comment]
If `kubectl logs` works and there are timeouts I'd do what you are doing: investigate the networking.

Where is your kubernetes cluster hosted or is it one you installed yourself/base metal? I'm not super familiar with lower level k8s things but maybe there is a helm chart or something that runs a kind of stress test for the networking in the cluster. Thinking of [memtest86](https://en.wikipedia.org/wiki/Memtest86) but for networking (not sure if that exists but it would be great if it did)

**Comment by shibbas** [comment]
I'm trying this out on Azure.

**Comment by manics** [comment]
Hi :wave: This is an old issue which doesn't sound like a BinderHub bug so I'm closing it. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
