### ISSUE TITLE
Better document how builds are done and when dind should be used

### ISSUE THREAD

**Issue by chicocvenancio** [jupyterhub/binderhub#832]
I ran into #761 a few weeks ago and got stuck there until @minrk suggest configuring it to use dind.
This is not mentioned in the documentation, so perhaps we should mention it there 😄 .

**Comment by jhamman** [comment]
+1, we're currently working on getting dind fixed up in binder.pangeo.io and some docs on the subject would likely help.

xref: https://github.com/pangeo-data/pangeo-binder/pull/47#issuecomment-485990721

**Comment by betatim** [comment]
Maybe you can document your steps and pitfalls as you implement this for pangeo. Then we'd have a starting point for the documentation on how to setup DIND.

**Comment by jhamman** [comment]
see #838 for a pass at some docs on this subject.

**Comment by jhamman** [comment]
Another question related to the binderhub DinD implementation. What is the expected behavior of the daemonset in terms of scaling? Should we expect one dind pod per build pod, per node, etc? Anecdotally, I'm seeing one dind and one image-cleaner pod per node.

**Comment by betatim** [comment]
A daemonset is the kubernetes way of saying "run one instance of this pod on each node in the cluster" (there are some subtleties and special cases but I think we should gloss over those). Worth linking to https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/.

One DIND pod provides one docker daemon that multiple build pods can use. So I think in theory you could run just one DIND pod for the whole cluster or only run them on some of the nodes. However we want to spread the load of building images around so that is why there is one per node. It is also the simplest setup :)

**Comment by jhamman** [comment]
Thanks @betatim. That clears things up for me. I think we (pangeo, maybe also mybinder) will want to restrict the dind daemonset to a single node pool (https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#running-pods-on-only-some-nodes). For example, we don't need/want the `dind` pods in our pool of dask workers.

**Comment by betatim** [comment]
Nods. You could also imagine running the builds on spot instances instead of "long lived" nodes.

In the mybinder.org setup we already have it configured so the core node pool (where we run the hub pods and other "core" stuff) don't have a DIND pod on them https://github.com/jupyterhub/mybinder.org-deploy/blob/52ffd5f02d74b0d040c33f592903c38d94d6f39e/config/prod.yaml#L11
