### ISSUE TITLE
Set up a binderhub gitter?

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/binderhub#84]
At some point we should have a communication channel for real-time Binder chatter that isn't attached to `binder-project`. Does it make sense for this repo to have a Gitter channel, and to start directing people there instead of to the current Gitter room? It's going to be a kind of awkward transition either way but I think it'll be less-so the earlier we do it.

@willingc WDYT about this?

**Comment by choldgraf** [comment]
@yuvipanda suggested that we create another repository simply called `binder` that will be used as a user-facing POC for the Binder ecosystem. I think that's a good idea so that there's one place users can go to. Thoughts?

**Comment by willingc** [comment]
I do think a dedicated Binder channel would be helpful. I'm not that familiar with what exists out there to support users right now with Binder. Let me recap my understanding and let's iterate from there:

1. Existing binder support channels and repos would be deprecated and folks directed to the new channels/repos for "BinderHub" based Binder. Timeline: Before official beta of "BinderHub" Binder (BHB - abbreviating as this for rest of issue)
2. Create a user facing gitter channel for BHB. Timeline: Before official beta of BHB. Current proposal is to create a `jupyterhub/binder` repo.
3. `jupyterhub/binder` repo: What contents would this repo contain? I'm wondering if/when it might make sense to create a GitHub org for Binder. @minrk, thoughts?

**Comment by minrk** [comment]
>  I'm wondering if/when it might make sense to create a GitHub org for Binder

We already have one at @binder-project. Should we be moving things over there? If it should be a dedicated org, is there a reason for it to be a new one instead of the existing one?

**Comment by willingc** [comment]
Good point @minrk. I forgot about the existing org. I unsure how many repos will be associated with Binder. If it's a bunch it may make sense to have it as an org vs. under JupyterHub org. @choldgraf/@yuvipanda, Thoughts?

**Comment by choldgraf** [comment]
I think @yuvipanda had thoughts on this the last time we discussed it. I don't have super strong opinions either way, though the original binder project had a bunch of repos that comprised the Binder tech, whereas now it's split between JHub, binderhub, and repo2docker, so I'm not sure that warrants its own organization.

I guess I see a couple options:

1. Sunset `binder-project` and create a repo in jupyterhub called `binder` that will be the funnel for user contact for the public binder
2. Move all binder-related things to `binder-project` and sunset all of the old binder repositories.
3. Keep `binder-project` as is and only modify the main `binder` repo so that it serves the purposed described in number 1. Keep all the binder guts in jupyterhub.

Thoughts?

**Comment by yuvipanda** [comment]
I don't want us to re-use the binder-project org if at all possible, just
to avoid confusion with old binder tech (which already happens). We have to
preserve the old repos for posterity, so I would rather let that whole org
be as is.

 I generally think it is too early to use a different org - we only have
one repo that can be in a new org (binderhub) since repo2docker should stay
in Jupyter. We already have too many orgs in project jupyter and I think we
should keep it from exploding if we can :) Consolidating the binder project
into jupyter org structure was something I was very happy about, I hope we
can keep that :)

The reason I suggested having a 'mybinder' repo is that a lot of people
just want 'support for using binder', not 'participate in building
binderhub'. This new repo would be analogous to the jupyter/jupyter repo /
gitter or jupyter/help. This also helps people have a place to file support
tickets and help each other with getting binders working as they want them
to. If this is too confusing tho we can just use jupyterhub/binderhub. That
is what we do for jupyterhub...

**Comment by choldgraf** [comment]
that sounds reasonable to me

**Comment by willingc** [comment]
Sounds like a plan. So to recap:

1. Create a new repo: `jupyterhub/mybinder` or `jupyterhub/binder` - Your choice
2. Create a gitter channel for that repo and use it to support questions from people using the new binder.
3. Leave binder-project.org as a historical org with notes added to the READMEs as suggested by @choldgraf to redirect to new binder gitter channel and repo.

**Comment by choldgraf** [comment]
+1

I cam initiate this today. Can somebody make me an administrator on
JupyterHub?

**Comment by willingc** [comment]
@choldgraf Just added you. If you have any issue with permissions, please let me know.

**Comment by willingc** [comment]
Closing as https://gitter.im/jupyterhub/binder is now active.
