### ISSUE TITLE
Add anchors to filepath?

### ISSUE THREAD

**Issue by kteich-oreilly** [jupyterhub/binderhub#850]
Is it possible to, when using `filepath=` to open a specific file, specify a section/anchor to jump to? For example, if I have this in my file `myfile.ipynb`:

`<a id='section2'></a>`

I'd love to be able to use `filepath=myfile.ipynb#section2` to open that file to that anchor.

It looks like something currently sees `#` in `filepath` and redirects me to a prompt to enter a token or password. I've tried various things with `urlpath` as well.

Thanks!

**Comment by betatim** [comment]
Hi.

My guess is that you'd have to escape/encode the `#` so that it becomes part of the value passed to `filepath` instead of being interpreted by your browser as part of the launch URL itself. Have you tried that?

**Comment by kteich-oreilly** [comment]
Him Tim, thanks for the reply.

The actual URL generated by the BinderHub portal form looks like this:
`http://...?filepath=myfile.ipynb%23section2`
So the `#` is being escaped. But following it leads to the prompt to enter a token or password.

If I use another arbitrary character like pipe, the URL looks like:
`http://...?filepath=myfile.ipynb%7Csection2`
and it leads to a 404 page, but the server is started. If I then manually change the resulting URL from:
`http://.../tree/myfile.ipynb%7Csection2`
to
`http://.../tree/myfile.ipynb#section2`
it loads the right file and jumps to the right section.

So it seems like the escaped `#` is doing something specific to lead to the prompt for a token. I'm not sure exactly what that page is doing, we'll dig into that. But it seems like this is almost working, so I'm wondering if I'm doing something wrong. Or, if it's something that could be working with a minor change, we'll look into that.

Thanks!

**Comment by bitnik** [comment]
BinderHub uses a token to access to the notebook server for each launch (for each temporary user). Just before redirecting to user server, it logs "server running at .../tree?token=xyz". But in your case server url becomes "/tree/myfile.ipynb#section2?token=xyz" and because token parameter is behing `#`, it is ignored and you are redirected to login page. So I think it is now not possible to have a file path with anchor.

To have it working the server url must be generated as "/tree/myfile.ipynb?token=xyz#section2" and I think this can be achived by updating here: https://github.com/jupyterhub/binderhub/blob/5544f704cb0dd9b8d3d67442a0c744e1ddcb6089/binderhub/static/js/src/image.js#L37-L58

**Comment by kteich-oreilly** [comment]
Thanks Kenan, that's super helpful.

**Comment by fabiencelier** [comment]
I had the same issue with a urlpath redirect containing a `#` on mybinder
I try to redirect directly to a running app that uses [react hash router](https://reactrouter.com/web/api/HashRouter)

**Comment by manics** [comment]
Hi :wave: I think this is something that has to be handled by the application (JupyterLab or notebook), not BinderHub. If you have more questions please use the [Jupyter community forum https://discourse.jupyter.org/](https://discourse.jupyter.org/).
