### ISSUE TITLE
How-to guide for setting up a private container repository

### ISSUE THREAD

**Issue by sgibson91** [jupyterhub/binderhub#869]
Hi!

I was wondering, is a step-by-step guide for deploying and connecting a private docker container repository (from Google or Azure, etc.) within the scope of the BinderHub docs? Or should we just include links to tutorials? (Happy to write the Azure docs if yes.)

**Comment by betatim** [comment]
Would that be adding to https://binderhub.readthedocs.io/en/latest/setup-registry.html#set-up-the-container-registry? If yes I think we should add an Azure section to this.

For me there is a difference between using a registry (like mybinder.org does on GCP) and operating&using a registry (like mybinder.org does on OVH). I'd love some guides on the latter but I think it should be in a different section of the docs than what users see in the first setup guide. Mostly because I think running your own registry is hard work.

**Comment by sgibson91** [comment]
Yep, that would be where I'd put these docs.

I'm just doing some experiments as there's some service principal stuff that I'm I'm not sure whether you _have_ to do during (or before) the cluster deployment.  If this is going to involve updating the Zero to JupyterHub with Kubernetes docs as well, I think we'll need to meditate on exactly the best way to present this info, or even if we still should. (Azure specific awkwardness!)

I'm also keen to write some sort of script that will clean out images older than X days and have it be run automatically every month by, say, CI or a DevOps pipeline. But that's future work.

**Comment by betatim** [comment]
re: old images, there is https://github.com/jupyterhub/mybinder.org-deploy/blob/master/scripts/delete-old-images.py which we (manually) use for mybinder.org. Might have something useful in it or even do most of the job.

**Comment by sgibson91** [comment]
PR open at #878 🎉
