### ISSUE TITLE
Widget failing in Shiny app

### ISSUE THREAD

**Issue by pablobernabeu** [jupyterhub/binderhub#968]
*One week earlier posted [on the Community](https://discourse.jupyter.org/t/widget-failing-in-shiny-app/2226).*

Hello!

I would like to ask for help with an error I get in a Shiny app when (and only when) it is run through the Binder RStudio. The error affects a drop-down menu titled ‘Dominant modalities’, in which the three color-coded categories are replaced by quote marks. 

Below is a screenshot of what the drop-down list should look like, as it does when the app is run from a local RStudio:

![8b301ff915e84f6080de77cffd6fa592be1d8d88](https://user-images.githubusercontent.com/20436359/65987575-fee55c80-e47d-11e9-8bda-efc680575f74.png)

This is what it looks like on Binder RStudio:

![Screenshot 2019-10-01 at 19 10 41](https://user-images.githubusercontent.com/20436359/65989130-ffcbbd80-e480-11e9-8b4e-9b72bc223545.png)

This drop-down is based on the R package *shinyWidgets*, which I loaded in the app script as well as in the install.R doc. Also, I’m using the latest version of R (having set it in the runtime.txt file). RStudio is slightly older, though, but I don’t think that could cause this error (could it?).

If you have a moment to look at this, would you please follow these steps:

1. Visit the [repo on the Binder RStudio](https://mybinder.org/v2/gh/pablobernabeu/Modality-exclusivity-norms-747-Dutch-English-replication/master?urlpath=rstudio);
    - If you wish, look at the code for the Shiny app by opening the ‘Shiny-app’ folder in the ‘Files’ box on the right, and selecting the script ‘Dutch-modality-exclusivity-norms.rmd’;
2. Run app by calling  `rmarkdown::run('./Shiny-app/Dutch-modality-exclusivity-norms.rmd')` on the RStudio console.

Thank you very much indeed

**Comment by betatim** [comment]
Replied in the forum http://discourse.jupyter.org/ (where most of the people who hang out here also hang out, as well as more people) and closing this issue. We are trying to streamline the [different discussion places](https://discourse.jupyter.org/t/a-proposal-for-jupyterhub-communications/505) and want to use the issues on GitHub repos for technical discussions on how to change the contents of the repo. More general discussions should go to discourse so that they are easier to find, better indexed by google and generally more accessible than being hidden in the bowls of a GitHub repository ;)

Thanks!
